Update reports

diff --git a/reports/wilson.ci.chef.co/job/chef-backend-trigger-git_poll/179.yaml b/reports/wilson.ci.chef.co/job/chef-backend-trigger-git_poll/179.yaml
--- a/reports/wilson.ci.chef.co/job/chef-backend-trigger-git_poll/179.yaml
+++ b/reports/wilson.ci.chef.co/job/chef-backend-trigger-git_poll/179.yaml
@@ -2,10 +2,11 @@
 result: FAILURE
 url: http://wilson.ci.chef.co/job/chef-backend-trigger-git_poll/179/
 failure_category: code
-failure_cause: 'chef-client: all: chef-backend-test'
+failure_cause: 'chef-client: chef-backend-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-backend,role=tester;
+  chef-client: all: chef-backend-test'
 timestamp: 2016-04-22 10:50:10 UTC
 duration: 33m53s
-active_duration: 33m38s
+active_duration: 59m26s
 parameters: {}
 change:
   git_remote: git@github.com:chef/chef-backend.git
@@ -13,6 +14,193 @@ change:
   project: chef-backend
   version: 0.4.0+20160422105025.git.25.77efa99
 stages:
+  chef-backend-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-backend,role=builder:
+    result: SUCCESS
+    url: http://wilson.ci.chef.co/job/chef-backend-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-backend,role=builder/212/
+    duration: 14m21s
+  chef-backend-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-backend,role=tester:
+    result: FAILURE
+    failure_category: code
+    failure_cause: chef-client
+    failed_in:
+      step: chef-client
+    url: http://wilson.ci.chef.co/job/chef-backend-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-backend,role=tester/201/
+    duration: 11m26s
+    logs:
+      consoleText:
+        571: |
+          [2016-04-22T11:19:41+00:00] INFO: GET /organizations/chef/nodes/ip-10-194-12-189.us-west-2.compute.internal
+          [2016-04-22T11:19:41+00:00] INFO: #<ChefZero::RestErrorResponse: 404: Object not found: chefzero://localhost:8889/nodes/ip-10-194-12-189.us-west-2.compute.internal>
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.6.1/lib/chef_zero/rest_base.rb:91:in `rescue in get_data'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.6.1/lib/chef_zero/rest_base.rb:83:in `get_data'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.6.1/lib/chef_zero/endpoints/rest_object_endpoint.rb:18:in `get'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.6.1/lib/chef_zero/rest_base.rb:62:in `call'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.6.1/lib/chef_zero/rest_router.rb:24:in `call'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.6.1/lib/chef_zero/server.rb:664:in `block in app'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.6.1/lib/chef_zero/server.rb:336:in `call'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.6.1/lib/chef_zero/server.rb:336:in `handle_socketless_request'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.6.1/lib/chef_zero/socketless_server_map.rb:87:in `request'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.6.1/lib/chef_zero/socketless_server_map.rb:33:in `request'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/http/socketless_chef_zero_client.rb:154:in `request'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/http.rb:305:in `block in send_http_request'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/http.rb:336:in `block in retrying_http_errors'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/http.rb:334:in `loop'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/http.rb:334:in `retrying_http_errors'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/http.rb:299:in `send_http_request'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/http.rb:144:in `request'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/http.rb:111:in `get'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/node.rb:604:in `load'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/node.rb:588:in `find_or_create'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/client.rb:465:in `load_node'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/client.rb:267:in `run'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/application.rb:267:in `run_with_graceful_exit_option'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/application.rb:243:in `block in run_chef_client'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/local_mode.rb:44:in `with_server_connectivity'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/application.rb:226:in `run_chef_client'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/application/client.rb:419:in `run_application'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/lib/chef/application.rb:58:in `run'
+          /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.13/bin/chef-client:26:in `<top (required)>'
+          /opt/opscode/embedded/bin/chef-client:23:in `load'
+          /opt/opscode/embedded/bin/chef-client:23:in `<main>'
+          [2016-04-22T11:19:41+00:00] INFO:
+          --- RESPONSE (404) ---
+        4338: |2
+
+                    if attempt == 120
+                        raise 'ERROR: Timeout waiting for DRBD mount to return'
+                    end
+                    print '.'
+        5128: |
+          if File.exists?("/etc/opscode/chef-server.json") &&
+              !(File.exist?("/etc/opscode/private-chef.rb") || File.exist?("/etc/opscode/chef-server.rb"))
+            Chef::Log.fatal("Configuration via /etc/opscode/chef-server.json is not supported. Please use /etc/opscode/chef-server.rb")
+            exit!(1)
+          else
+        5942: |2
+            [2016-04-22T11:19:43+00:00] INFO: Storing updated cookbooks/private-chef/recipes/ctl_config.rb in the cache.
+            if !connected
+                Chef::Log.fatal("HAProxy status socket never appeared properly!")
+                Chef::Log.fatal("See /var/log/opscode/haproxy/current for more information")
+                Kernel.exit! 1
+              end
+        5993: |2
+
+              if !stable
+                Chef::Log.fatal("HAProxy still showing multiple active backends")
+                Chef::Log.fatal("Please check /var/log/opscode/haproxy/current locally for problems.")
+                Chef::Log.fatal("Please check your backend cluster's status for problems.")
+                Kernel.exit! 1
+              end
+        6783: |2
+              rescue Exception => e
+                message = <<-EOF
+          ERROR:
+          The /var/opt/opscode/upgrades/migration-level file is missing or corrupt!  Please read http://docs.chef.io/install_server_pre.html and correct this file before proceeding
+        7390: |2
+                # use of exit! prevents exit handlers from running, ensuring the last thing
+                # the customer sees is the descriptive error we've provided.
+                Chef::Log.fatal("\n\n#{LINE_SEP}\n#{e.message}#{LINE_SEP}")
+                exit! 128
+              end
+        7647: |2
+                  `echo 'SELECT * FROM pg_database;' | su - #{node['private_chef']['postgresql']['username']} -c '/opt/opscode/embedded/bin/psql -p #{node['private_chef']['postgresql']['port']} -U #{node['private_chef']['postgresql']['db_superuser']} postgres -t -A'`
+            if $?.exitstatus != 0
+                    Chef::Log.fatal("Could not connect to database, retrying in 10 seconds.")
+                    sleep 10
+                  else
+        7656: |2
+
+                unless connectable
+                  Chef::Log.fatal <<-ERR
+
+          Could not connect to the postgresql database.
+        9184: |2
+                  elsif PrivateChef['backend_vips']['ipaddress'] =~ /\:/
+                    # IPv6 addresses must have the mask
+                    Chef::Log.fatal("backend_vip ipaddress field appears to be a IPv6 address without a netmask  (e.g /64, /48)")
+                    exit 66
+                  else
+        9197: |2
+              def generate_hex_if_bootstrap(chars, ha_guard)
+                if ha_guard
+                  Chef::Log.fatal("Attempt to create secrets on non-bootstrap node in an H/A topology, please copy /etc/opscode/* around instead.")
+                  exit 44
+                end
+        9586: |2
+              def assert_server_config(node_name)
+                unless PrivateChef["servers"].key?(node_name)
+                  Chef::Log.fatal <<-EOF
+          No server configuration found for "#{node_name}" in /etc/opscode/chef-server.rb.
+          Server configuration exists for the following hostnames:
+        9613: |2
+                    gen_api_fqdn
+                  else
+                    Chef::Log.fatal("I do not understand topology #{PrivateChef.topology} - try standalone, manual, ha, or tier.")
+                    exit 55
+                  end
+        15892: |2
+
+          #------------------------------------------------------------------------------
+          # ERROR REPORTING AND LOGGING
+          #------------------------------------------------------------------------------
+        15963: |2
+                    #   error
+                    #   log
+                    #   fatal
+                    #   panic
+        15977: |2
+                    #   error
+                    #   log
+                    #   fatal
+                    #   panic (effectively off)
+        16167: |2
+
+          #------------------------------------------------------------------------------
+          # ERROR HANDLING
+          #------------------------------------------------------------------------------
+        17226: |2
+
+            if [ ! -d "$OCF_ROOT" ]; then
+              ha_log "ERROR: OCF_ROOT points to non-directory $OCF_ROOT."
+              exit $OCF_ERR_GENERIC
+            fi
+        17246: |2
+
+            if [ -z "$OCF_RESOURCE_INSTANCE" ]; then
+              ha_log "ERROR: Need to tell us our resource instance name."
+              exit $OCF_ERR_ARGS
+            fi
+        17283: |2
+                    loglevel=notice
+                    case "${*}" in
+                      *ERROR*)    loglevel=err;;
+                      *WARN*)   loglevel=warning;;
+                      *INFO*|info)  loglevel=info;;
+        17382: |2
+                  case "${__OCF_PRIO}" in
+                    crit) __OCF_PRIO="CRIT";;
+                    err)  __OCF_PRIO="ERROR";;
+                    warn) __OCF_PRIO="WARNING";;
+                    info) __OCF_PRIO="INFO";;
+        30182: |2
+
+            if node['fqdn'].nil?
+              Chef::Log.fatal("This node's fqdn is set to nil, so a read token cannot be issued!" \
+                              "Please change your fqdn settings.")
+            end
+        31087: |
+          [2016-04-22T11:19:50+00:00] INFO: runit_service[haproxy] enabled
+          [2016-04-22T11:20:21+00:00] INFO: Processing ruby_block[wait for haproxy status socket] action run (private-chef::haproxy line 91)
+          [2016-04-22T11:20:31+00:00] FATAL: HAProxy status socket never appeared properly!
+          [2016-04-22T11:20:31+00:00] FATAL: See /var/log/opscode/haproxy/current for more information
+          Build step 'Invoke XShell command' marked build as failure
+          Performing Post build task...
+          Match found for : : True
+    steps:
+      total: 11m26s
+      before (setup time): 10m31s
+      after (cleanup time): 51s
   chef-backend-test:
     result: FAILURE
     failure_category: code
